require('dotenv').config();
const mongoose = require('mongoose');
const { notifyAdmins } = require('./controllers/notificationController');

async function testNotifications() {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/nivasa_society');
    console.log('Connected to DB');

    await notifyAdmins({
        title: 'Test Admin Notification',
        message: 'This is a test notification generated by the system script.',
        type: 'info',
        relatedModel: 'Other'
    });

    console.log('Fired test notification to admins');
    process.exit(0);
}

testNotifications().catch(console.error);
